PROPERTIES_RENAME_DICT = {
    'parcelid': 'id_parcel',
    'yearbuilt': 'build_year',
    'basementsqft': 'area_basement',
    'yardbuildingsqft17': 'area_patio',
    'yardbuildingsqft26': 'area_shed',
    'poolsizesum': 'area_pool',
    'lotsizesquarefeet': 'area_lot',
    'garagetotalsqft': 'area_garage',
    'finishedfloor1squarefeet': 'area_firstfloor_finished',
    'calculatedfinishedsquarefeet': 'area_total_finished_calc',
    'finishedsquarefeet6': 'area_basic',
    'finishedsquarefeet12': 'area_live_finished',
    'finishedsquarefeet13': 'area_liveperi_finished',
    'finishedsquarefeet15': 'area_total_finished',
    'finishedsquarefeet50': 'area_live_entry_finished',
    'unitcnt': 'num_unit',
    'numberofstories': 'num_story',
    'roomcnt': 'num_room',
    'bathroomcnt': 'num_bathroom',
    'bedroomcnt': 'num_bedroom',
    'calculatedbathnbr': 'num_bathroom_calc',
    'fullbathcnt': 'num_bathroom_full',
    'threequarterbathnbr': 'num_bathroom_quarter',
    'fireplacecnt': 'num_fireplace',
    'poolcnt': 'num_pool',
    'garagecarcnt': 'num_garage',
    'regionidcounty': 'region_county',
    'regionidcity': 'region_city',
    'regionidzip': 'region_zip',
    'regionidneighborhood': 'region_neighbor',
    'taxvaluedollarcnt': 'tax_total',
    'structuretaxvaluedollarcnt': 'tax_building',
    'landtaxvaluedollarcnt': 'tax_land',
    'taxamount': 'tax_property',
    'assessmentyear': 'tax_year',
    'taxdelinquencyflag': 'tax_flag_delinquency',
    'taxdelinquencyyear': 'tax_delinquency_year',
    'propertyzoningdesc': 'zoning_property',
    'propertylandusetypeid': 'zoning_landuse',
    'propertycountylandusecode': 'zoning_landuse_county',
    'fireplaceflag': 'flag_fireplace',
    'hashottuborspa': 'flag_tub',
    'buildingqualitytypeid': 'quality',
    'buildingclasstypeid': 'framing',
    'typeconstructiontypeid': 'material',
    'decktypeid': 'deck',
    'storytypeid': 'story',
    'heatingorsystemtypeid': 'heating',
    'airconditioningtypeid': 'aircon',
    'architecturalstyletypeid': 'architectural_style',
}

TRANSACTION_RENAME_DICT = {
    'parcelid': 'id_parcel',
    'transactiondate': 'date'
}

NUMERICAL_COLS = [
    'build_year',
    'area_basement',
    'area_patio',
    'area_shed',
    'area_pool',
    'area_lot',
    'area_garage',
    'area_firstfloor_finished',
    'area_total_finished_calc',
    'area_basic',
    'area_live_finished',
    'area_liveperi_finished',
    'area_total_finished',
    'area_live_entry_finished',
    'num_unit',
    'num_story',
    'num_room',
    'num_bathroom',
    'num_bedroom',
    'num_bathroom_calc',
    'num_bathroom_full',
    'num_bathroom_quarter',
    'num_fireplace',
    'num_pool',
    'num_garage',
    'tax_total',
    'tax_building',
    'tax_land',
    'tax_property',
    # 'tax_year',  # only one value, deleted
    'tax_delinquency_year',
    'quality',
]

CATEGORICAL_COLS = [
    'region_county',
    'region_city',
    'region_zip',
    'region_neighbor',
    'tax_flag_delinquency',
    'zoning_property',
    'zoning_landuse',
    'zoning_landuse_county',
    'flag_fireplace',
    'flag_tub',
    'framing',
    'material',
    'deck',
    'story',
    'heating',
    'aircon',
    'architectural_style',
]
